In [1]:
import numpy as np
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [2]:
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [4]:
# 1.2.1
round(apartment[-1], 2)

0.53

In [6]:
# 1.2.2
apartment.shape

(5,)

In [9]:
# 1.3.3
alexey_income = np.array([120, 150, 90])
wife_income = np.array([130, 130, 130])
mil_eur_income = np.array([2, 3, 2.5])
exchange_rate = 72

mil_rub_income = mil_eur_income * exchange_rate
mil_rub_income
overall_income = alexey_income + wife_income + mil_rub_income
overall_income

array([394., 496., 400.])

In [10]:
# 1.4.1
v1 = np.array([4,5])
v2 = np.array([2,1])
v3 = np.array([1,0])
result = v1*2+v2*(-3)+v3*5
result

array([7, 7])

In [12]:
# 1.4.2

income = 400
expences = -200
build = np.array([3, 4, 5, 9])
sold = np.array([1, 5, 3, 6])
result = build*expences+sold*income
result

array([-200, 1200,  200,  600])

In [16]:
53**0.5

7.280109889280518